#!/bin/bash
echo "USAGE: ./script SOURCE_DATE END_DATE"
echo "SCRIPT takes two dates make a new file under /m/Desktop/G named o_SOURCE_DATE-END_DATE.txt contains EN then space then G"
file=/m/Desktop/G/o.txt
new_file_dir=/m/Desktop/G
if [ $2 ]

then
/bin/cp $file /tmp/o.txt

sd=`echo $1|grep -o ..$`
ed=`echo $2|grep -o ..$`
bd=`echo $1|grep -o ^......`

p=$sd
rm -rf /tmp/matched
while [ $p -le $ed ]
do
	grep ${bd}$p /tmp/o.txt >> /tmp/matched
	pp=$(($p + 1))
	p=`printf "%02d" $pp`

done
cat /tmp/matched |cut -d- -f2 > o1
cat /tmp/matched |cut -d- -f3 > o2
counter=`wc -l o1|cut -d" "  -f1`
for i in `seq $counter`;do echo -n E- ;sed -n ${i}p o1;echo ; echo -n G-; sed -n ${i}p o2 ;done > /m/Desktop/G/o_$1-$2.txt
	cp /m/Desktop/G/o_$1-$2.txt /m/Desktop/G/o_latest.txt


else
	echo PLEASE READ USAGE
	read
	exit

fi



