#!/bin/bash

#output file to be saved in in the form of D  --- E
output=/m/Desktop/G/o.txt
echo "script tp input words, phrases to be saved in a file $output "
read -e k



while true
do
	clear
tput setaf 2
echo  'D --> ' 
tput setaf 3
read -e   D
clear
grep -i "\- $D$" $output 1>/dev/null 2>&1
if [ $? -eq 0 ]
then
	echo `grep -i "\- $D$" $output|cut -d"-" -f2,3|head -1`
	read -e h
	continue
fi
clear
echo  "$D "
tput setaf 2
echo  "-->> " 
tput setaf 4
#echo -n 
read -e  E

echo "`date '+%Y%m%d'` - $E - $D" 
read -e -n 1 -t 1 j
if [ "$j" == "" ]
then
echo "`date '+%Y%m%d'` - $E - $D" >> $output
cp -f $output /var
fi
done
